### ISSUE TITLE
Toolbox namespaces/packages

### ISSUE THREAD

**Issue by rtopfer** [shimming-toolbox/shimming-toolbox-matlab#84] opened 2020-05-20 21:04 UTC
I think it would be sensible to group aspects of the Toolbox into namespaces/libraries. 

Matlab does this by prepending folder names with "+" to become ["packages"](https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html).

I propose packaging at least what I see as the 3 main modules:

1. "+img": preliminary file I/O, image processing stuff (formerly mostly within the `MaRdI` class +`FieldEval` subclass). E.g., just dealing with NIfTI's, there's MATLAB's `niftiread`, plus the NIfTI_Toolbox (which users may already have installed on their path), so rather than be forced to avoid using the existing function names or worrying about path precedence, we can just place our own `niftiread`/`load_nii` equivalents in our custom package (e.g. the call could look like `img.load_nii`)

2. "+b0sc": b0 shim coil stuff (everything in the ["Coils"](https://github.com/shimming-toolbox/shimming-toolbox/tree/master/Coils) folder—specific coils could probably be their own subpackages). (E.g., a call to `ShimSpecs` would now look like `b0sc.ShimSpecs`.) 

3. "+ui": higher-level command line and GUI material for actual experimental sessions.

I don't know if the Toolbox itself should also be packaged—I'm leery of using subpackages all over the place since it seems awkward: every single piece of code then needs to reference the exact package of every of piece of code, even when they're part of the same package. [Some people](https://www.mathworks.com/matlabcentral/answers/280234-misleading-wording-in-the-documentation-on-matlab-package-folders) seem to think Matlab packages are too much of a hassle for this reason. (For the same reason, it seems considerably more convenient for programming to keep the package names short abbreviations; obvious drawback being that package names are likely to be less explicitly descriptive)

**Comment by jcohenadad** [comment] 2020-05-20 21:16
> I think it would be sensible to group aspects of the Toolbox into namespaces/libraries.
> 
> Matlab does this by prepending folder names with "+" to become ["packages"](https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html).

it sounds awesome 👍 

> 1. "+img": preliminary file I/O, image processing stuff (formerly mostly within the `MaRdI` class +`FieldEval` subclass). E.g., just dealing with NIfTI's, there's MATLAB's `niftiread`, plus the NIfTI_Toolbox (which users may already have installed on their path), so rather than be forced to avoid using the existing function names or worrying about path precedence, we can just place our own `niftiread`/`load_nii` equivalents in our custom package (e.g. the call could look like `img.load_nii`)

i'm not sure i understand the rationale. E.g., if we impose dependency to Matlab's `niftiread`, why would we need a wrapper for it? Is it because we need to accommodate special cases such as dealing with 4d data (e.g. in case we point to a folder with a bunch of 3D volumes, each representing an echo)

Also, do we still need to depend on NIfTI_Toolbox?

Lastly: I guess the img package would also deal with converting dicoms (via a wrapper that calls dcm2niix, e.g. `img.convert_dicom_to_nifti`)

> 2. "+b0sc": b0 shim coil stuff (everything in the ["Coils"](https://github.com/shimming-toolbox/shimming-toolbox/tree/master/Coils) folder—specific coils could probably be their own subpackages). (E.g., a call to `ShimSpecs` would now look like `b0sc.ShimSpecs`.)

not a big fan of the name b0sc (unclear what "sc" is, and we might use this same package for b1-- to be confirmed). How about "+coil" or "+shim"

> 3. "+ui": higher-level command line and GUI material for actual experimental sessions.

👍 

> I don't know if the Toolbox itself should also be packaged—I'm leery of using subpackages all over the place since it seems awkward: every single piece of code then needs to reference the exact package of every of piece of code, even when they're part of the same package. [Some people](https://www.mathworks.com/matlabcentral/answers/280234-misleading-wording-in-the-documentation-on-matlab-package-folders) seem to think Matlab packages are too much of a hassle for this reason. (For the same reason, it seems considerably more convenient for programming to keep the package names short abbreviations; obvious drawback being that package names are likely to be less explicitly descriptive)

maybe we can go iteratively, with the obvious subpackages, and then reassess later on?

**Comment by rtopfer** [comment] 2020-05-20 21:32
> i'm not sure i understand the rationale. E.g., if we impose dependency to Matlab's `niftiread`, why would we need a wrapper for it? Is it because we need to accommodate special cases such as dealing with 4d data (e.g. in case we point to a folder with a bunch of 3D volumes, each representing an echo)


Maybe/probably for the 3d/4d cases. Immediate wrapper application is just to look for + load the accompanying .json along with the image + header. (And _possibly_ to automatically rescale/recast phase images from int16 into doubles in radians, though, this could happen in a separate function file. Working on this currently.)
 
> 
> Also, do we still need to depend on NIfTI_Toolbox?

Don't think we'll need it. But if other users have it installed already and we want to use the same function names then using packages would just help to avoid potential conflicts. (NIfTI_toolbox might not be the best example here, but this sort of thing does come up occasionally—usually it's that I want to name a function something but Matlab has already claimed it.)

> Lastly: I guess the img package would also deal with converting dicoms (via a wrapper that calls dcm2niix, e.g. `img.convert_dicom_to_nifti`)

👍

> not a big fan of the name b0sc (unclear what "sc" is, and we might use this same package for b1-- to be confirmed). How about "+coil" or "+shim"

I agree, but if b1 shimming becomes part of the functionality as a _separate package_ then "+shim" or "+coil" is ambiguous...
 
> 
> maybe we can go iteratively, with the obvious subpackages, and then reassess later on?

👍

**Comment by jcohenadad** [comment] 2020-07-01 01:26
duplicate of https://github.com/shimming-toolbox/shimming-toolbox/issues/148

**Closed as completed by jcohenadad** 2020-07-01 01:26 UTC
Labels: design
